before:
  hooks:
    - go mod tidy
builds:
  - id: powwy-cli
    main: ./cmd/powwy-cli
    binary: powwy-cli
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}} -extldflags '-static'

  - id: powwy-srv
    main: ./cmd/powwy-srv
    binary: powwy-server
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X main.version={{.Version}} -extldflags '-static'

archives:
  - id: powwy-srv
    builds:
      - powwy-srv
    name_template: "powwy-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: MacOSX
      linux: Linux
      windows: Windows
      amd64: x86_64

  - id: powwy-cli
    builds:
      - powwy-cli
    name_template: "powwy-cli{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: MacOSX
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: robotomize
    name: powwy